### ISSUE TITLE
System not runing to the end 

### ISSUE THREAD

**Issue by falaFulani** [hengsin/idempiere-dev-setup#1]
Hello, 
I am installing the system as per your guidelines. However it seems to be stuck at this point (as per attached pic). 

Kindly help 
![github](https://user-images.githubusercontent.com/24565265/72051353-272df400-32d4-11ea-82b7-5cdf17fdad80.png)

**Comment by hengsin** [comment]
just wait for it to load completely, as the message say, it will took a
while ...

if that stall for a very long time, that's probably due to you have a slow
network connection.

**Comment by falaFulani** [comment]
Noted with thanks.
