### ISSUE TITLE
Update db setup script add auto complete support

### ISSUE THREAD

**Issue by hengsin** [hengsin/idempiere-dev-setup#14]
- remove the use of = (i.e --db-port 54321 instead of --db-porrt=54321) and add auto complete support for scripts.
- update postgresql docker container image setup to version 15.3
- update setup-db.sh for JAVA_OPTIONS

**Comment by eusme** [comment]
Sir i am looking help specifically from you if you may! about idempiere-dev-setup project. "echo "Bad postgres admin password and couldn't connect to idempiere database $DB_NAME using the provided credential." this is the only message i got when i try to setup.sh. please!!

**Comment by eusme** [comment]
I will wait for your reply. Thank you Sir

**Comment by eusme** [comment]
I am encountering the problem that i face in connection database is in all this 3 versions -->  idempiere-2023-12, idempiere-2024-03,idempiere-2024-06

my OS Debian 12, Rocky 9. in both the same issue. Thank you

**Comment by eusme** [comment]
Sir this script "setup-db.sh" may be the only issue that i face it may need you genuine 10 minutes help. Me i try it days which i couldn't fix it. your 10 min change many thing in my side.  good day

**Comment by eusme** [comment]
CONTAINER ID   IMAGE           COMMAND                  CREATED              STATUS              PORTS                                       NAMES
e3fbd8972191   postgres:15.3   "docker-entrypoint.s…"   About a minute ago   Up About a minute   0.0.0.0:5432->5432/tcp, :::5432->5432/tcp   postgres

**Comment by eusme** [comment]
Any help please!
