### ISSUE TITLE
Database Set-Up

### ISSUE THREAD

**Issue by falaFulani** [hengsin/idempiere-dev-setup#2]
Hey there again, 
The database details provided in the set up are somehow in correct. 
![db_test](https://user-images.githubusercontent.com/24565265/72056270-59901f00-32dd-11ea-98f3-e6d3a6a10029.png)
![error](https://user-images.githubusercontent.com/24565265/72056271-5a28b580-32dd-11ea-943e-9b184eadf0df.png)

**Comment by falaFulani** [comment]
I have created a new db and user in the setup-db.sh file and everything is a Green.

**Comment by hengsin** [comment]
By default, the script is using postgres as the value for postgresql administrator password. If that's not the case, you have to set the environment variable DB_SYSTEM before execution of the setup script (export DB_SYSTEM=<your postgresql admin passwor>).

**Comment by falaFulani** [comment]
Quick question, 
I want to do a migration of the database seed. how do I go about it.

**Comment by hengsin** [comment]
what kind of migration do you means here ?

**Comment by falaFulani** [comment]
How do you solve this problem (attached). 
![Uploading h.png…]()

**Comment by falaFulani** [comment]
![h](https://user-images.githubusercontent.com/24565265/72155661-a1d63c80-33c4-11ea-974a-ea2b1f30c645.png)

**Comment by hengsin** [comment]
you have not enter the correct password for postgres user. if you don't have the password and you have already created the idempiere database, you can turn on the "DB Already Exists" checkbox to proceed.

**Comment by falaFulani** [comment]
Hello, 
checking "Db Already exists" does not import the data into the database. 

Also, i noticed the database created from the setup is not listed when runing the command "\l" in psql terminal

**Comment by hengsin** [comment]
I'm just referring to the dialog you posted above and do note that, the dialog doesn't import data, it just setup your db connection profile (idempiere.properties).

**Comment by falaFulani** [comment]
Now I understand you. Kindly advise on how to import the data into the database. Thank you
