### ISSUE TITLE
org.adempiere.server.feature Error

### ISSUE THREAD

**Issue by falaFulani** [hengsin/idempiere-dev-setup#3]
Hello
I am still going through your code step by step in order to understand it. 

After downloading eclipse, the code runs "mvn verify" to build the platform. However, as per today (16th Jan 2020), the following error (attached) is returned. 

Could you help. 
![error](https://user-images.githubusercontent.com/24565265/72522326-7b098180-386e-11ea-958c-55e1b5b448e6.png)

**Comment by hengsin** [comment]
yes, this is an idempiere error. as of now, the idempiere pom is broken due
to this recent maven repo changes -
https://support.sonatype.com/hc/en-us/articles/360041287334

**Comment by falaFulani** [comment]
Which files in the idempiere directory, do I have to change?

**Comment by hengsin** [comment]
no, I means that's a bug from the idempiere project, you got to wait for
the fix from idempiere. anyway, if you are interested, it is the pom.xml
that need fixing.

**Comment by falaFulani** [comment]
Waiting for the fix from idempiere may take longer. I am interested in knowing how to modify the pom.xml file

**Comment by hengsin** [comment]
fix already committed, you can try again now.
