### ISSUE TITLE
URL to provide Groovy not accessible

### ISSUE THREAD

**Issue by tony-tspc** [hengsin/idempiere-dev-setup#8]
In the file setup.sh, the URL to download Groovy (https://dl.bintray.com/groovy/maven/apache-groovy-binary-3.0.7.zip) is not publically accesible. I get a "forbidden" access error.
I was able to get the same version from the following URL: https://archive.apache.org/dist/groovy/3.0.7/distribution/apache-groovy-binary-3.0.7.zip

**Comment by hengsin** [comment]
thanks, updated as suggested

**Comment by tony-tspc** [comment]
thanks
